version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://wallet_user:wallet_pass@postgres:5432/walletai_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # AI Service
  ai-service:
    build: ./ai-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./ai-service:/app

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_pass
      - POSTGRES_DB=walletai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: